#define INST_ADDR_START     0
#define USRSYS_STACK_START  0x00100000 // USR, SYS 모드 스택
#define SVC_STACK_START     0x00300000 // SVC 모드 스택
#define IRQ_STACK_START     0x00400000 // IRQ 모드 스택
#define FIQ_STACK_START     0x00500000 // FIQ 모드 스택
#define ABT_STACK_START     0x00600000 // ABT 모드 스택
#define UND_STACK_START     0x00700000 // UND 모드 스택 
#define TASK_STACK_START    0x00800000 // 태스크 영역 스택
#define GLOBAL_ADDR_START   0x04800000 // 전역변수 영역 스택
#define DALLOC_ADDR_START   0x04900000 // 동적할당 영역 스택
// 각각의 스택 사이즈를 계산
#define INST_MEM_SIZE       (USRSYS_STACK_START - INST_ADDR_START) 
#define USRSYS_STACK_SIZE   (SVC_STACK_START - USRSYS_STACK_START)
#define SVC_STACK_SIZE      (IRQ_STACK_START - SVC_STACK_START)
#define IRQ_STACK_SIZE      (FIQ_STACK_START - IRQ_STACK_START)
#define FIQ_STACK_SIZE      (ABT_STACK_START - FIQ_STACK_START)
#define ABT_STACK_SIZE      (UND_STACK_START - ABT_STACK_START)
#define UND_STACK_SIZE      (TASK_STACK_START - UND_STACK_START)
#define TASK_STACK_SIZE     (GLOBAL_ADDR_START - TASK_STACK_START)
#define DALLOC_MEM_SIZE     (55 * 1024 * 1024)
// 스택의 TOP을 처리하는 부분
#define USRSYS_STACK_TOP    (USRSYS_STACK_START + USRSYS_STACK_SIZE  - 4)
#define SVC_STACK_TOP       (SVC_STACK_START + SVC_STACK_SIZE - 4)
#define IRQ_STACK_TOP       (IRQ_STACK_START + IRQ_STACK_SIZE - 4)
#define FIQ_STACK_TOP       (FIQ_STACK_START + FIQ_STACK_SIZE - 4)
#define ABT_STACK_TOP       (ABT_STACK_START + ABT_STACK_SIZE - 4)
#define UND_STACK_TOP       (UND_STACK_START + UND_STACK_SIZE - 4)
